### ISSUE TITLE
Selecionar um caso de uso para ser implementado na SPRINT 1. Escrever os fluxos alternativos para o caso de uso selecionado.

### ISSUE THREAD

**Issue by tmsasaki** [RodrigoPoliveira/ppads-projeto-05j-2018s2#1]

**Comment by zucchi25** [comment]
CDU001 - CADASTRAR FRRELA

FLUXO ORIGINAL
Insere Titulo -> Selecionar Categoria -> Insere Descrição do Freela -> Insere especificação do Freela -> Insere prazo de entrega -> Insere valor ofertado

FLUXO ALTERNATIVO
Insere Titulo ->> Selecionar Categoria Outros -> Escreve a categoria no campo-> Insere Descrição do Freela -> Insere especificação do Freela -> Insere prazo de entrega -> Insere valor ofertado

**Comment by tmsasaki** [comment]
No documento casos-de-uso.md, faltou incluir o comportamento do sistema.

**Comment by zucchi25** [comment]
FLUXO ORIGINAL
Insere Titulo -> Selecionar Categoria -> Insere Descrição do Freela -> Insere especificação do Freela -> Insere prazo de entrega -> Insere valor ofertado -> Registra no banco

FLUXO ALTERNATIVO
Insere Titulo ->> Selecionar Categoria Outros -> Escreve a categoria no campo-> Insere Descrição do Freela -> Insere especificação do Freela -> Insere prazo de entrega -> Insere valor ofertado -> Registra no banco
