### ISSUE TITLE
Elaborar um DIAGRAMA DE IMPLANTAÇÃO (DEPLOYMENT DIAGRAM) da solução.

### ISSUE THREAD

**Issue by tmsasaki** [RodrigoPoliveira/ppads-projeto-05j-2018s2#8]
Dica: procurar por DEPLOYMENT DIAGRAM UML para ver alguns exemplos.

**Comment by zucchi25** [comment]
![image](https://user-images.githubusercontent.com/28466435/48308500-b105f400-e54d-11e8-9e98-f4252dc13573.png)

**Comment by tmsasaki** [comment]
Colocar o diagrama na pasta /docs

**Comment by zucchi25** [comment]
Postado na pasta /docs
